language: android
android:
  components:
  - build-tools-19.1.0               # BuildTools version
  - android-19                       # SDK version
  - sys-img-armeabi-v7a-android-19   # System image
script:
  - cat /etc/ld.so.preload
  - adb devices
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb devices

notifications:
  email:
  - bin.jinb@alibaba-inc.com
