language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - rbx

script: ruby -v && more /proc/cpuinfo | grep processor && free -m
after_script: echo $TRAVIS_TEST_RESULT

branches:
  only:
  - master
notifications:
  email:
  - bin.jinb@alibaba-inc.com
