language: java
services:
  - riak     # will start riak
  - rabbitmq # will start rabbitmq-server
  - memcached 
env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
  - HELLO=world
  - TEST_SUITE=test
  - TEST_SUITE=test
script: echo "bundle exec rake test:$TEST_SUITE"
